name: Scala CI

on:
  push:
    branches:
      - master
      - 8Pattern
  pull_request:
    branches:
      - master
      - 8Pattern

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: compile
      run: sbt compile
    - name: Run tests with coverage and upload to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export CI_BRANCH="${GITHUB_REF#refs/heads/}"
        sbt coverage test
        sbt coverageReport
        sbt coveralls
