language: scala
scala:
- 2.12.7

script:
- sbt clean coverage test coverageReport

after_success:
- sbt coverageReport coveralls

notifications:
  email:
    recipients:
      - bokelmanncornelius@web.de
    on_success: always
    on_failure: always
