language: scala
scala:
- 3.2.2

script:
- sbt clean coverage test coverageReport

after_success:
- sbt coverageReport coveralls

notifications:
  email:
    recipients:
      - bokelmanncornelius@web.de
    on_success: always
    on_failure: always